# Generated by Django 6.0 on 2025-12-31 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('PLASTIC', 'Plastic'), ('METAL', 'Metal'), ('GLASS', 'Glass')], max_length=10)),
                ('weight', models.FloatField()),
                ('machine_id', models.CharField(max_length=50)),
                ('points_earned', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
